version: "2"
services:
  my-mysql-db:
    image: "mysql:8"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "mydb"
    command: "--default-authentication-plugin=mysql_native_password"
  grafana:
    image: "grafana/grafana:7.0.4"
    environment:
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    ports:
      - "3000:3000"